### ISSUE TITLE
Second time more than %10 price slippage 

### ISSUE THREAD

**Issue by desperkatrina** [aragon/convert.aragon.org#42] opened 2020-07-21 19:32 UTC
This is my first txid: https://etherscan.io/tx/0x6966627757f39ae47b05e7ab9a80e7ba74358c972cf047cae4e0ff1f0dac34e0
And this is the second one https://etherscan.io/tx/0x476076a1ff88121da99f760661871b07f4d7a6eb374f6b6c57389f0e2ba11248

I took SS for this time. Please help me.

![anj 2](https://user-images.githubusercontent.com/55110087/88098160-fd6a5980-cba1-11ea-836d-a8bbd778c059.png)

**Comment by pain871** [comment] 2020-07-22 10:22
![IMG_20200722_070344](https://user-images.githubusercontent.com/25098804/88165110-60f69480-cc3f-11ea-8368-45cf9adfe902.jpg)
Same here
https://etherscan.io/tx/0x72f6835303901ad726b35a3b92a14056b1de8eca3ddbcfd28d68c064a47cd848
I should have received 492 ant,, but I only received 431 ant

**Comment by pain871** [comment] 2020-07-22 10:32
The trader will lose money because of this problem ... the trading results are very different from the estimation shown

**Comment by sohkai** [comment] 2020-07-22 10:42
Closing; duplicate of #41.

**Closed by sohkai** 2020-07-22 10:42 UTC

**Comment by desperkatrina** [comment] 2020-07-22 10:51
This is not the same issue here! https://github.com/aragon/convert.aragon.org/issues/41 isn't the exactly the same. And also there is SS on this ticket. So don't close it man!
